# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 825)
        MainWindow.setMinimumSize(QtCore.QSize(1040, 825))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 750, 750))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(780, 20, 221, 760))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_graficar = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_graficar.setGeometry(QtCore.QRect(30, 370, 150, 150))
        self.pushButton_graficar.setObjectName("pushButton_graficar")
        self.pushButton_reset = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_reset.setGeometry(QtCore.QRect(30, 560, 150, 150))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 50, 201, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_bias = QtWidgets.QLabel(self.groupBox_2)
        self.label_bias.setObjectName("label_bias")
        self.verticalLayout.addWidget(self.label_bias)
        self.lineEdit_bias = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_bias.setObjectName("lineEdit_bias")
        self.verticalLayout.addWidget(self.lineEdit_bias)
        self.label_w1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_w1.setObjectName("label_w1")
        self.verticalLayout.addWidget(self.label_w1)
        self.lineEdit_w1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_w1.setObjectName("lineEdit_w1")
        self.verticalLayout.addWidget(self.lineEdit_w1)
        self.label_w2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_w2.setObjectName("label_w2")
        self.verticalLayout.addWidget(self.label_w2)
        self.lineEdit_w2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_w2.setObjectName("lineEdit_w2")
        self.verticalLayout.addWidget(self.lineEdit_w2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 0, 55, 16))
        self.label.setObjectName("label")
        self.label_x1 = QtWidgets.QLabel(self.centralwidget)
        self.label_x1.setGeometry(QtCore.QRect(730, 360, 55, 16))
        self.label_x1.setObjectName("label_x1")
        self.label_nx2 = QtWidgets.QLabel(self.centralwidget)
        self.label_nx2.setGeometry(QtCore.QRect(380, 720, 55, 16))
        self.label_nx2.setObjectName("label_nx2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 360, 55, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Graficar"))
        self.pushButton_graficar.setText(_translate("MainWindow", "Graficar"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Entradas"))
        self.label_bias.setText(_translate("MainWindow", "Bias"))
        self.label_w1.setText(_translate("MainWindow", "W1"))
        self.label_w2.setText(_translate("MainWindow", "W2"))
        self.label.setText(_translate("MainWindow", "X2"))
        self.label_x1.setText(_translate("MainWindow", "X1"))
        self.label_nx2.setText(_translate("MainWindow", "-x2"))
        self.label_2.setText(_translate("MainWindow", "-x1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
